### ISSUE TITLE
Upgrade hipblas 0.5.2.0 to 0.6.0.8 via deb repository fails.

### ISSUE THREAD

**Issue by ptsant** [ROCmSoftwarePlatform/hipBLAS#35]
### What is the expected behavior
-  apt-get install hipblas should work

### What actually happens
```
The following packages will be upgraded:
  hipblas
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
4 not fully installed or removed.
Need to get 0 B/62.1 kB of archives.
After this operation, 270 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
(Reading database ... 1092339 files and directories currently installed.)
Preparing to unpack .../hipblas_0.6.0.8_amd64.deb ...
Unpacking hipblas (0.6.0.8) over (0.5.2.0) ...
dpkg: error processing archive /var/cache/apt/archives/hipblas_0.6.0.8_amd64.deb (--unpack):
 unable to open '/opt/rocm/hipblas/lib/cmake/hipblas/hipblas-config-version.cmake.dpkg-new': No such file or directory
abort-upgrade
Errors were encountered while processing:
 /var/cache/apt/archives/hipblas_0.6.0.8_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

### How to reproduce
-  Standard upgrade from previous ROCm version via the repository. 

### Environment
Linux mint 18.2

**Comment by kknox** [comment]
In the older .deb packages (< v0.6), we had problems in the packaging uninstall scripts that left some files around.  Symlinks and such were left hanging.  I believe these install/uninstall issues are fixed in any version > v0.6.  Unfortunately, the v0.6.0.8 package can't fix the bugs in the v0.5.2 package you have installed.  

Btw, we never released an official v0.5 .deb series (an odd number means our develop branch), so you must have built that one by source yourself.  Please manually uninstall the v0.5 package (through dpkg --purge), and scan through the /opt/rocm directory to make sure that hipblas looks gone adn all dangling symlinks are removed.

**Comment by kknox** [comment]
No further comments have been made; closing.

**Comment by ptsant** [comment]
Hello, sorry for not responding right away. 

Thanks for the help! The problem went away when I removed some old symbolic links. The package installed correctly.
