### ISSUE TITLE
add topic tags

### ISSUE THREAD

**Issue by Beliavsky** [ROCmSoftwarePlatform/hipBLAS#817]
I suggest adding topics such as `rocm`, `blas`, `cuda` in the About section at https://github.com/ROCm/hipBLAS

**Comment by daineAMD** [comment]
Hi @Beliavsky,

You can take a look at the [hipBLAS Documentation](https://rocm.docs.amd.com/projects/hipBLAS/en/latest/index.html), you may find what you're looking for in the [Introduction](https://rocm.docs.amd.com/projects/hipBLAS/en/latest/index.html) or in the [hipBLAS API Docs](https://rocm.docs.amd.com/projects/hipBLAS/en/latest/functions.html).

Otherwise, can you be more specific in what you'd expect to find in the documentation that's missing? Also, are you referring to the [README](https://github.com/ROCm/hipBLAS/blob/develop/README.md) when you say "the About section"?

Thanks for your feedback,
Daine

**Comment by Beliavsky** [comment]
How to add topics is described at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics . It enables your project to be found with a topic search.

**Comment by daineAMD** [comment]
Great, I've added the tags you've suggested. Thanks very much!
